### ISSUE TITLE
Disable sleep

### ISSUE THREAD

**Issue by dmd** [jabyrd3/dashboard-from-scratch#22]
Can you please disable sleep mode?
Example: https://github.com/richtr/NoSleep.js

**Comment by dmd** [comment]
It needs a user event handler, so tie it to tap so when it goes fullscreen it also won't go to sleep.

**Comment by jabyrd3** [comment]
seems to be working? hard to debug, trying in ios simulator but its slow going

**Comment by dmd** [comment]
Closed by https://github.com/jabyrd3/dashboard-from-scratch/commit/34d1e24797c3bc1c751b671544ab3aa5a11234bb
