### ISSUE TITLE
ignore TriageStatus we don't recognize

### ISSUE THREAD

**Issue by dmd** [jabyrd3/dashboard-from-scratch#23]
The original spec said:

"For each item, draw a bar of TriageStatus color (Red, Green, or Blue - if it says something else, ignore that record). ...   There is one more color: White."

However, the app currently fails (goes orange) if TriageStatus is the empty string.

Can you please update so "if it says something else" (besides Red|Green|Blue|White), "ignore the record"?

**Comment by jabyrd3** [comment]
it was supposed to do this already, had a paren scoping bug.

Fixed now.
