### ISSUE TITLE
config minBars

### ISSUE THREAD

**Issue by dmd** [jabyrd3/dashboard-from-scratch#3]
If minBars is 10, then if there are 5 entries, you will draw those 5 entries but also draw 5 zero-length bars at the bottom (so basically add 5 zero length blue bars) in order to pad things out.

This of course must happen AFTER you do the "if age is less than 10 minutes, make age 10 minutes" thing, because they should be truly zero length.

**Comment by jabyrd3** [comment]
handled this slightly differently than outlined here for maintainability; basically if there are fewer than 7 bars, it uses different multipliers to calculate the bar height.
